sudo: required
services:
  - docker

before_install:
  - docker build -t node-project .

script:
  - docker run node-project npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1" # where you created bean stalk
  app: "docker" # name you give when created elastic bean stalk
  bucket_name: "elasticbeanstalk-u-west-2-306476627547" # bucket created when creates bean stalk"
  bucket_path: "docker" 
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY  # add into travis env variable in setting of pipeline
  secret_access_key: 
    secret: $AWS_SECRET_KEY  # add into travis env variable in setting of pipeline

